# Utiliza la imagen base de Node.js
FROM node:18-bullseye

# Define el directorio de trabajo
WORKDIR /src

# Copia los archivos package.json y package-lock.json (o solo package.json si no usas package-lock.json)
COPY package*.json ./

# Instala las dependencias del proyecto, incluyendo las de desarrollo
RUN npm install

# Copia el resto de los archivos del proyecto
COPY . .

# Compilar el código TypeScript (si es necesario)
RUN npm run build

# Listar archivos en el dist
RUN ls -l dist/

# Exponer el puerto en el que se ejecuta la aplicación
EXPOSE 8081

# Utilizar nodemon para recarga en vivo en desarrollo
CMD [ "node", "dist/index.js" ]